
CC = gcc
CFLAGS = -Wall
INCFLAGS = -I. -I/usr/include -I/usr/include/libxml2
LIBS = -ldl -lxml2 -lcrypto

all: main.o 
	$(CC) $(LIBS) -o test main.o 

main.o: main.c
	$(CC) -c $(CFLAGS) $(INCFLAGS) main.c

clean:
	rm test main.o
